These steps are taken from this link : https://365datascience.com/tutorials/how-to-build-recommendation-system-in-python/

In [3]:
import pandas as pd

df = pd.read_csv('BX-Books.csv',error_bad_lines=False,encoding='latin-1',sep=';')
df.head()

/var/folders/gd/14rnhkrn05df7_144vtd5ljm0000gp/T/ipykernel_2122/555768930.py:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('BX-Books.csv',error_bad_lines=False,encoding='latin-1',sep=';')
Skipping line 6452: expected 8 fields, saw 9
Skipping line 43667: expected 8 fields, saw 10
Skipping line 51751: expected 8 fields, saw 9

Skipping line 92038: expected 8 fields, saw 9
Skipping line 104319: expected 8 fields, saw 9
Skipping line 121768: expected 8 fields, saw 9

Skipping line 144058: expected 8 fields, saw 9
Skipping line 150789: expected 8 fields, saw 9
Skipping line 157128: expected 8 fields, saw 9
Skipping line 180189: expected 8 fields, saw 9
Skipping line 185738: expected 8 fields, saw 9

Skipping line 209388: expected 8 fields, saw 9
Skipping line 220626: expected 8 fields, saw 9
Skipping line 227933: expected 8 fields, saw 11
Skipping line 228957: expected 8 fields, saw 10
Skipping line 245933: expected 8 fields, saw 9
Skipping line 251296: expected 8 fields, saw 9
Skipping line 259941: expected 8 fields, saw 9
Skipping line 261529: expected 8 fields, saw 9

/var/folders/gd/14rnhkrn05df7_144vtd5ljm0000gp/T/ipykernel_2122/555768930.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('BX-Books.csv',error_bad_lines=False,encoding='latin-1',sep=';')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:
#just checking info on the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271359 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [6]:
#checking how many duplicates are there
df.duplicated(subset='Book-Title').sum()

29225

In [11]:
#drop duplicate book entries
df = df.drop_duplicates(subset='Book-Title')

#after dropping checking again for the duplicates
df.duplicated(subset='Book-Title').sum()

0

In [12]:
#randomly sample 15,000 rows from the dataframe to avoid running into memory errors:

sample_size = 15000
df = df.sample(n=sample_size, replace=False, random_state=490)

df = df.reset_index()
df = df.drop('index',axis=1)

In [14]:
# check again for head after sampling
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0060972491,"Thank You, Jeeves",P.G. Wodehouse,1989,Perennial,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...
1,015602781X,Pincher Martin: The Two Deaths of Christopher ...,William Golding,2002,Harvest Books,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...
2,1561441627,The Nutcracker (Christmas Fun-to-Read Fairy Ta...,Roberta Collier-Morales,1992,Modern Publishing,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...
3,1402708610,I Know a Rhino,Charles Fuge,2003,Sterling,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...
4,0441586325,Norby and the Oldest Dragon,Janet Asimov,1993,Ace Books,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...

In [21]:
# The dataframe contains columns that are not relevant to the model, such as each book’s ISBN code, its year of publication, and a link to its image.

# We will only use the “Book-Title,” “Book-Author,” and “Publisher” columns to build the model. 

# Since this is text data, we need to transform it into a vector representation. In simple terms, this means that we will convert text into its numeric representation before we can apply predictive modeling techniques onto it.

# We will create a vector of numbers using Scikit-Learn’s CountVectorizer:
# [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

In [22]:
#'''
#Before converting the data into a word vector, we need to clean it. 
#First, let’s remove whitespaces from the “Book-Author” column. 
#If we do not do this, then CountVectorizer will count the authors’ first and last name as a separate word.
#For instance, if one author is named James Clear and another is called James Patterson, the vectorizer will count the word James in both cases, and the recommender system might consider the books as highly similar, even though they are not related at all. James Clear writes self-help books while James Patterson is known for his mystery novels.
#'''

def clean_text(author):
    result = str(author).lower()
    return(result.replace(' ',''))
df['Book-Author'] = df['Book-Author'].apply(clean_text)

In [25]:
#Now, let’s convert the book title and publisher to lowercase:

df['Book-Title'] = df['Book-Title'].str.lower()
df['Publisher'] = df['Publisher'].str.lower()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0060972491,"thank you, jeeves",p.g.wodehouse,1989,perennial,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...
1,015602781X,pincher martin: the two deaths of christopher ...,williamgolding,2002,harvest books,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...
2,1561441627,the nutcracker (christmas fun-to-read fairy ta...,robertacollier-morales,1992,modern publishing,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...
3,1402708610,i know a rhino,charlesfuge,2003,sterling,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...
4,0441586325,norby and the oldest dragon,janetasimov,1993,ace books,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...
...,...,...,...,...,...,...,...,...
14995,1572240687,taking the anxiety out of taking tests: a step...,susanjohnson,1997,new harbinger pubns inc,http://images.amazon.com/images/P/1572240687.0...,http://images.amazon.com/images/P/1572240687.0...,http://images.amazon.com/images/P/1572240687.0...
14996,157356303X,encyclopedia of women's health issues,kathlyngay,2001,oryx press,http://images.amazon.com/images/P/157356303X.0...,http://images.amazon.com/images/P/157356303X.0...,http://images.amazon.com/images/P/157356303X.0...
14997,067900856X,fodor's 2002 new york city (fodor's new york c...,fodors,2001,fodor's travel publications,http://images.amazon.com/images/P/067900856X.0...,http://images.amazon.com/images/P/067900856X.0...,http://images.amazon.com/images/P/067900856X.0...
14998,0156232057,"c. s. lewis: a biography,revised edition",rogerlancelyngreen,1995,harcourt,http://images.amazon.com/images/P/0156232057.0...,http://images.amazon.com/images/P/0156232057.0...,http://images.amazon.com/images/P/0156232057.0...
14999,0060984163,the late night muse: a novel,bettepesetsky,1993,harpercollins,http://images.amazon.com/images/P/0060984163.0...,http://images.amazon.com/images/P/0060984163.0...,http://images.amazon.com/images/P/0060984163.0...

In [30]:
#Finally, let’s combine these three columns to create a single variable:

# combine all strings:
df2 = df.drop(['ISBN','Image-URL-S','Image-URL-M','Image-URL-L','Year-Of-Publication'],axis=1)

df2['data'] = df2[df2.columns[1:]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)

print(df2['data'].head())

0                     p.g.wodehouse perennial
1                williamgolding harvest books
2    robertacollier-morales modern publishing
3                        charlesfuge sterling
4                       janetasimov ace books
Name: data, dtype: object

,Book-Title,Book-Author,Publisher
0,"thank you, jeeves",p.g.wodehouse,perennial
1,pincher martin: the two deaths of christopher ...,williamgolding,harvest books
2,the nutcracker (christmas fun-to-read fairy ta...,robertacollier-morales,modern publishing
3,i know a rhino,charlesfuge,sterling
4,norby and the oldest dragon,janetasimov,ace books
...,...,...,...
14995,taking the anxiety out of taking tests: a step...,susanjohnson,new harbinger pubns inc
14996,encyclopedia of women's health issues,kathlyngay,oryx press
14997,fodor's 2002 new york city (fodor's new york c...,fodors,fodor's travel publications
14998,"c. s. lewis: a biography,revised edition",rogerlancelyngreen,harcourt
14999,the late night muse: a novel,bettepesetsky,harpercollins

In [31]:
#Finally, we can apply Scikit-Learn’s CountVectorizer() on the combined text data:

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorized = vectorizer.fit_transform(df2['data'])

#The variable “vectorized” is a sparse matrix with a numeric representation of the strings we extracted.

In [34]:
#Now, we will use a distance measure called cosine similarity to find the resemblance between each bag-of-words. 
#Cosine similarity is a metric that calculates the cosine of the angle between two or more vectors to determine if 
#they are pointing in the same direction.

#Cosine similarity ranges between 0 and 1. A value of 0 indicates that the two vectors are not similar at all, while 1 tells us that they are identical.

#Run the following lines of code to apply cosine similarity on the vector we created:

from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(vectorized)
#Now, print the “similarities” variable:

print(similarities)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [36]:
#We have a vector of values ranging between 1 and 0, and each vector represents the similarity of one book relative to another. Since the book titles are not mentioned here, we need to map this vector back to the previous dataframe:

df = pd.DataFrame(similarities, columns=df['Book-Title'], index=df['Book-Title']).reset_index()

df.head()

Book-Title,Book-Title,"thank you, jeeves",pincher martin: the two deaths of christopher martin,the nutcracker (christmas fun-to-read fairy tales ser),i know a rhino,norby and the oldest dragon,his eminence and hizzoner,el oro de los sueã±os (leer en espaã±ol nivel 4),celestine insights,feng shui and money: a nine-week program for creating wealth using ancient principles and techniques,...,"the santa suit (harlequin american romance, no. 708)",where the gods reign: plants and peoples of the colombian amazon,the terrible troll-bird,virginia embrace (magnolia road),"take 5, volume 4 (under the knife, adam's gift, return to yesterday, everything but time, marriage diamond style)",taking the anxiety out of taking tests: a step-by-step guide,encyclopedia of women's health issues,fodor's 2002 new york city (fodor's new york city),"c. s. lewis: a biography,revised edition",the late night muse: a novel
0,"thank you, jeeves",1.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,pincher martin: the two deaths of christopher ...,0.0,1.000000,0.0,0.0,0.333333,0.288675,0.000000,0.288675,0.0,...,0.0,0.0,0.235702,0.288675,0.0,0.0,0.0,0.0,0.0,0.0
2,the nutcracker (christmas fun-to-read fairy ta...,0.0,0.000000,1.0,0.0,0.000000,0.000000,0.223607,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,i know a rhino,0.0,0.000000,0.0,1.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,norby and the oldest dragon,0.0,0.333333,0.0,0.0,1.000000,0.288675,0.000000,0.288675,0.0,...,0.0,0.0,0.235702,0.288675,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
#Finally, let’s use the dataframe above to display book recommendations. 
#If a book is entered as input, the top 10 similar books must be returned.

#Let us do this using a book from the Star Trek series as input:

input_book = 'far beyond the stars (star trek deep space nine)'
recommendations = pd.DataFrame(df.nlargest(11,input_book)['Book-Title'])
recommendations = recommendations[recommendations['Book-Title']!=input_book]
print(recommendations)

                                             Book-Title
768    to storm heaven (star trek: the next generation)
802   the star trek chronology : a history of the fu...
1472           gateways #1:  one small step (star trek)
2051           reunion (star trek: the next generation)
2891                marooned (star trek voyager, no 14)
3727     maelstrom (ultima: the technocrat war, book 3)
3991         belle terre (star trek: new earth, book 2)
4567  the way of the warrior (star trek deep space n...
4757  a rock and a hard place:star trek next generat...
5812               the joy machine (star trek, book 80)